version: "3.7"
networks:
  default:
    name: kisslog-net
    driver_opts:
      com.docker.network.driver.mtu: 1380

services:
  backend:
    image: catalingavan/kisslog.backend:6.0.0-beta4
    container_name: kisslog.backend.dev
    restart: unless-stopped
    volumes:
      - ./backend.appsettings.json:/app/appsettings.json
      - ./backend.KissLog.json:/app/Configuration/KissLog.json
    ports:
      - "44088:80"
    links:
      - "mongodb"

  frontend:
    image: catalingavan/kisslog.frontend:6.0.0-beta5
    container_name: kisslog.frontend.dev
    restart: unless-stopped
    volumes:
      - ./frontend.appsettings.json:/app/appsettings.json
      - ./frontend.KissLog.json:/app/Configuration/KissLog.json
    ports:
      - "44080:80"
    links:
      - "backend"

  mongodb:
    image: mongo:6.0.4
    container_name: kisslog.mongodb.dev
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
  mongo-config:

